### ISSUE TITLE
ERROR - java.lang.AssertionError: <<00009000>>

### ISSUE THREAD

**Issue by BuffaloWill** [Hannah-PortSwigger/RetrieveSiteMap#1]
Hi!

I am getting an AssertionError when I use the extension in Burp Enterprise. I am pretty sure it's being generated from this line:

https://github.com/Hannah-PortSwigger/RetrieveSiteMap/blob/4096a3483b60ebba04f4457560c394387b235447/src/main/java/burp/BurpExtender.java#L44

```
        IHttpRequestResponse[] reqRespArr = callbacks.getSiteMap(null);
```

Does this extension still work in the newest version of Burp Enterprise?

Cheers!

The partial stack trace is:
```
2023-08-01 21:34:52 [w] INFO  - Exception report:
2023-08-01 21:34:52 [w] INFO  -     Category: FAILED_ASSERTION
2023-08-01 21:34:52 [w] INFO  -     Detail:
2023-08-01 21:34:52 [w] ERROR - java.lang.AssertionError: <<00009000>>
2023-08-01 21:34:52 [w] INFO  - 	at net.portswigger.Z_6.Zc(Unknown Source)
2023-08-01 21:34:52 [w] INFO  - 	at net.portswigger.Z_6.ZY(Unknown Source)
2023-08-01 21:34:52 [w] INFO  - 	at burp.Zojc.ZL(Unknown Source)
2023-08-01 21:34:52 [w] INFO  - 	at burp.Zojc.ZB(Unknown Source)
2023-08-01 21:34:52 [w] INFO  - 	at burp.Zg3o.Zw(Unknown Source)
2023-08-01 21:34:52 [w] INFO  - 	at burp.Zq0k.requestResponses(Unknown Source)
2023-08-01 21:34:52 [w] INFO  - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-08-01 21:34:52 [w] INFO  - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
2023-08-01 21:34:52 [w] INFO  - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
2023-08-01 21:34:52 [w] INFO  - 	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
2023-08-01 21:34:52 [w] INFO  - 	at burp.Zrd5.invoke(Unknown Source)
2023-08-01 21:34:52 [w] INFO  - 	at jdk.proxy2/jdk.proxy2.$Proxy38.requestResponses(Unknown Source)
2023-08-01 21:34:52 [w] INFO  - 	at burp.Zoqq.getSiteMap(Unknown Source)
```

**Comment by Hannah-PortSwigger** [comment]
Hi.

Thanks for letting me know. I've replicated the issue, and will look into this further.

**Comment by Hannah-PortSwigger** [comment]
After further investigation, it looks like this is caused due to an issue in Burp. We've raised a bug report for this behavior and will endeavor to get this sorted out as soon as possible.

This will likely impact any extension for Burp Suite Enterprise Edition using the unload handler.

**Comment by Hannah-PortSwigger** [comment]
Apologies for the lack of update, but this issue should definitely be sorted now.

Additionally, this extension has now been rewritten to use the Montoya API.
